#!/bin/bash

batch=$(($1+1 + ($2-1)*10))
bs=100


for distr in lognormal normal gamma logistic; do
for label in pow size; do # size pow
for rho in  0 0.5 0.8; do # 0 0.5 0.8 0.9 0.95
  
  # for power
  if [ $label = "pow" ]; then 
  if [ $distr = "logistic" ]; then
    param=".6,$rho,1"
  else if [ $distr = "normal" ]; then
    param=".3,$rho,1"
  else if [ $distr = "lognormal" ]; then
    param=".3,$rho,1"
  else if [ $distr = "gamma" ]; then
    param="0.36,3,3,1,1,$rho"
  fi
  fi
  fi
  fi
  fi
  
  # for size
  if [ $label = "size" ]; then 
  if [ $distr = "logistic" ]; then
    param="0,$rho,1"
  else if [ $distr = "normal" ]; then
    param="0,$rho,1"
  else if [ $distr = "lognormal" ]; then
    param="0,$rho,1"
  else if [ $distr = "gamma" ]; then
    param="0,3,3,1,1,$rho"
  fi
  fi
  fi
  fi
  fi
  
  R -q --vanilla --args $bs $batch 20  10  0   $distr   $param   $label <partially_matched_test_MC.R >logs/5050$batch.out 2>logs/5050$batch.err
  R -q --vanilla --args $bs $batch 20  40  0   $distr   $param   $label <partially_matched_test_MC.R >logs/5050$batch.out 2>logs/5050$batch.err
  
  R -q --vanilla --args $bs $batch 20  10  5   $distr   $param   $label <partially_matched_test_MC.R >logs/5050$batch.out 2>logs/5050$batch.err
  R -q --vanilla --args $bs $batch 20  40  5   $distr   $param   $label <partially_matched_test_MC.R >logs/5050$batch.out 2>logs/5050$batch.err
  R -q --vanilla --args $bs $batch 20  10 10   $distr   $param   $label <partially_matched_test_MC.R >logs/5050$batch.out 2>logs/5050$batch.err

QWERTY
done
done
done




